version: "3.8"

services:
  pgdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "sleep 5 && python app.py"  # wait for DB
#    command: python app.py
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: tasksdb
      DB_HOST: pgdb
    depends_on:
      - pgdb
